# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
title: Commons Fabric Project
description: A resource hub for the Commons Fabric Project
theme: jekyll-theme-merlot
remote_theme: pages-themes/merlot
baseurl: "" #  subpath of your site, e.g. /blog
plugins:
  - jekyll-feed
  - jekyll-remote-theme
